name: Flutter CI

on:
  push:
    branches: [ "Developer/DuongHuy" ]
  pull_request:
    branches: [ "Developer/DuongHuy" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Cài đặt Flutter SDK (channel stable)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3' # Hoặc version bạn dùng
          channel: 'stable'
      
      # Lấy dependencies
      - name: Install dependencies
        run: flutter pub get

      # Kiểm tra format code (tùy chọn)
      - name: Verify formatting
        run: flutter format --set-exit-if-changed .

      # Phân tích static code
      - name: Analyze project source
        run: flutter analyze

      # Chạy unit test
      - name: Run tests
        run: flutter test
